In [1]:
import pandas as pd
import numpy as np

In [2]:
age = [10,20,30,35,40,45,50,55,59,60,65,69,70,75,33,57,82,29,80,85,90,95,100,18,24,26,36,44,48,52,66,15]

In [3]:
len(age)

32

In [4]:
age_mean = np.mean(age)

In [5]:
age_mean

51.96875

# now here see example of one sampled- t-test so we going to select some random saple from age data list 

In [6]:
sample_size = 10

In [7]:
age_sample = np.random.choice(age,sample_size)

In [8]:
age_sample

array([57, 70, 95, 75, 75, 36, 82, 85, 36, 90])

In [9]:
from scipy.stats import ttest_1samp 

In [10]:
# here we given two parameter first our randomly picked up sample and second is our mean of total age data list
t_test, p_value = ttest_1samp(age_sample,52)

In [11]:
p_value

0.02281575772266696

In [12]:
t_test

2.7408516611593012

In [13]:
# here we considering our p value or alpha value is 0.05 or 5 % BELOW This null hypothesis is rejected 
if p_value<=0.05:
    print('we are rejecting null hypothesis')
else:
    print('we are selecting all null hypothesis')

we are rejecting null hypothesis


# now we see two -sample t- test here 

In [14]:
np.random.seed(12)
school_age = stats.poisson.rvs(loc= 18, mu=35, size= 1500)
classA_age = stats.poisson.rvs(loc= 18, mu=30, size= 60)
CLASSB_age = stats.poisson.rvs(loc= 18, mu=33, size= 60)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [15]:
school_age.mean()

52.870666666666665

In [16]:
classA_age.mean()

46.75

In [17]:
CLASSB_age.mean()

50.083333333333336

In [18]:
from scipy.stats import ttest_ind

In [19]:
# here we taken two sample a and b in above exmp we took only one sample that is our age sample
t_test, p_value = ttest_ind(a= classA_age,b= CLASSB_age, equal_var= False)

In [20]:
p_value

0.002728967211474832

In [21]:
# here also we considering our p value or alpha value is 0.05 or 5 % BELOW This null hypothesis is rejected 
if p_value<=0.05:
    print('we are rejecting null hypothesis')
else:
    print('we are selecting null hypothesis')

we are rejecting null hypothesis


# now we see Chi Square testing 

In [22]:
df = pd.read_csv('tips.csv')

In [26]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [24]:
# chi square test is required where we consider two categorical variable and trying to find out wheter
# these two variable having any association b/w them  based on this we do for hypothesis testing 

In [25]:
# in above data set we going to find out whether any association b/w sex and smoker data

In [27]:
df_table = pd.crosstab(df['sex'],df['smoker'])

In [28]:
df_table

smoker  No  Yes
sex            
Female  54   33
Male    97   60

In [29]:
# observed value 
df_table.values

array([[54, 33],
       [97, 60]])

In [36]:
value = stats.chi2_contingency(df_table)

<IPython.core.display.Javascript object>

In [37]:
value

(0.008763290531773594,
 0.925417020494423,
 1,
 array([[53.84016393, 33.15983607],
        [97.15983607, 59.84016393]]))

In [38]:
expected_value = value[3]

In [39]:
expected_value

array([[53.84016393, 33.15983607],
       [97.15983607, 59.84016393]])

In [41]:
# rest we can see krish naik video lecture comp machine learning 155 slides video, slide no - 45 chi_sqare